### ISSUE TITLE
Haven't I already seen it?

### ISSUE THREAD

**Issue by Myzhar** [Road-Balance/rb_nanosaur#1]
This project is really "similar" to this Nanosaur:
https://nanosaur.ai/
https://github.com/rnanosaur/nanosaur

If you get inspiration from another open-source project you should at least cite it.

**Comment by kimsooyoung** [comment]
I apologize about that.  

I got a feedback from rbonghi about that and changed info too.

![image](https://user-images.githubusercontent.com/12381733/120253688-01d3c880-c2c3-11eb-91a8-c46812c212e5.png)

Thank you for notification.

**Comment by Myzhar** [comment]
Don't worry, the important is to understand and repair our faults... however, nice job! I can't wait to see amazing videos with your Nanosaur "evolution".

**Comment by kimsooyoung** [comment]
So much thank you for your consideration. 
Have a great day and Hope to safe 👍
